version: "3.7"

services:
  nginx:
    depends_on:
      - fastapi
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      # - "444:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/cert.pem:/etc/ssl/cert.pem       # <--- 공개키 볼륨 뚫어주기
      # - ./nginx/key.pem:/etc/ssl/key.pem         # <--- 개인키 볼륨 뚫어주기
      # - ./frontend:/usr/share/nginx/html         # <--- React build 후 생성된 파일 복사해서 fontend 디렉토리에 붙여넣을 것이므로 볼륨 뚫어주기
      
  fastapi:
    build: ./app
    restart: always
    container_name: fastapi

    # -------------------- uvicorn 에서 해당 명령어를 지원하므로 공개키, 기인키 경로 명시해주기 ------------------------
    command: uvicorn app.main:app --workers=16 --timeout-keep-alive=60 --host 0.0.0.0 --port 7000 --reload # --ssl-certfile /code/app/cert.pem --ssl-keyfile /code/app/key.pem --reload
    
    # 실행포트는 7003 외부 노출포트는 7000으로 설정 
    ports:
      - 7003:7000
    expose:
      - "7003"
    volumes:
      - ./app:/app